-- Repair model catalog reasoning metadata from a reviewed pi.dev snapshot.
-- source-sha256: 4c3693760c234130739781dfdc4adc0eb77d3a8b0215bd54d63b8aa035604752

WITH reviewed("canonical_model_id", "reasoning_bundle") AS (
  VALUES
    ('claude-haiku-4-5', '{"reasoning":true,"thinkingFormat":"anthropic"}'::jsonb),
    ('claude-opus-4-5', '{"reasoning":true,"thinkingFormat":"anthropic"}'::jsonb),
    ('claude-opus-4-5-20251101', '{"reasoning":true,"thinkingFormat":"anthropic"}'::jsonb),
    ('claude-opus-5', '{"reasoning":true,"thinkingFormat":"anthropic-adaptive","thinkingLevelMap":{"max":"max","xhigh":"xhigh"}}'::jsonb),
    ('claude-sonnet-4-5', '{"reasoning":true,"thinkingFormat":"anthropic"}'::jsonb),
    ('claude-sonnet-4-5-20250929', '{"reasoning":true,"thinkingFormat":"anthropic"}'::jsonb),
    ('deep-research-max-preview-04-2026', '{"reasoning":true,"thinkingFormat":"google"}'::jsonb),
    ('deep-research-preview-04-2026', '{"reasoning":true,"thinkingFormat":"google"}'::jsonb),
    ('gemini-2.5-computer-use-preview-10-2025', '{"reasoning":true,"thinkingFormat":"google"}'::jsonb),
    ('gemini-2.5-flash', '{"reasoning":true,"thinkingFormat":"google"}'::jsonb),
    ('gemini-2.5-flash-lite', '{"reasoning":true,"thinkingFormat":"google"}'::jsonb),
    ('gemini-2.5-pro', '{"reasoning":true,"thinkingFormat":"google"}'::jsonb),
    ('gemini-3-flash-preview', '{"reasoning":true,"thinkingFormat":"google","thinkingLevelMap":{"off":null}}'::jsonb),
    ('gemini-3.1-flash-lite', '{"reasoning":true,"thinkingFormat":"google","thinkingLevelMap":{"off":null}}'::jsonb),
    ('gemini-3.1-flash-lite-image', '{"reasoning":true,"thinkingFormat":"google","thinkingLevelMap":{"off":null}}'::jsonb),
    ('gemini-3.1-flash-live-preview', '{"reasoning":true,"thinkingFormat":"google","thinkingLevelMap":{"off":null}}'::jsonb),
    ('gemini-3.1-pro-preview', '{"reasoning":true,"thinkingFormat":"google","thinkingLevelMap":{"high":"HIGH","low":"LOW","medium":null,"minimal":null,"off":null}}'::jsonb),
    ('gemini-3.5-flash', '{"reasoning":true,"thinkingFormat":"google","thinkingLevelMap":{"off":null}}'::jsonb),
    ('gemini-3.5-flash-lite', '{"reasoning":true,"thinkingFormat":"google","thinkingLevelMap":{"off":null}}'::jsonb),
    ('gemini-3.6-flash', '{"reasoning":true,"thinkingFormat":"google","thinkingLevelMap":{"off":null}}'::jsonb),
    ('gemini-robotics-er-1.6-preview', '{"reasoning":true,"thinkingFormat":"google"}'::jsonb),
    ('gpt-5', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":"minimal","off":null,"xhigh":null}}'::jsonb),
    ('gpt-5-mini', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":"minimal","off":null,"xhigh":null}}'::jsonb),
    ('gpt-5-nano', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":"minimal","off":null,"xhigh":null}}'::jsonb),
    ('gpt-5-pro', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":null,"max":null,"medium":null,"minimal":null,"off":null,"xhigh":null}}'::jsonb),
    ('gpt-5.1', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":"none","xhigh":null}}'::jsonb),
    ('gpt-5.2', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":"none","xhigh":"xhigh"}}'::jsonb),
    ('gpt-5.2-chat-latest', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":null,"low":null,"max":null,"medium":"medium","minimal":null,"off":null,"xhigh":"xhigh"}}'::jsonb),
    ('gpt-5.2-pro', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":null,"max":null,"medium":"medium","minimal":null,"off":null,"xhigh":"xhigh"}}'::jsonb),
    ('gpt-5.3-codex', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":"none","xhigh":"xhigh"}}'::jsonb),
    ('gpt-5.3-codex-spark', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":null,"xhigh":"xhigh"}}'::jsonb),
    ('gpt-5.4', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":"none","xhigh":"xhigh"}}'::jsonb),
    ('gpt-5.4-mini', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":"none","xhigh":"xhigh"}}'::jsonb),
    ('gpt-5.4-nano', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":"none","xhigh":"xhigh"}}'::jsonb),
    ('gpt-5.4-pro', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":null,"max":null,"medium":"medium","minimal":null,"off":null,"xhigh":"xhigh"}}'::jsonb),
    ('gpt-5.5', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":"none","xhigh":"xhigh"}}'::jsonb),
    ('gpt-5.5-pro', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":null,"max":null,"medium":"medium","minimal":null,"off":null,"xhigh":"xhigh"}}'::jsonb),
    ('gpt-5.6-luna', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":"max","medium":"medium","minimal":null,"off":"none","xhigh":"xhigh"}}'::jsonb),
    ('gpt-5.6-sol', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":"max","medium":"medium","minimal":null,"off":"none","xhigh":"xhigh"}}'::jsonb),
    ('gpt-5.6-terra', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":"max","medium":"medium","minimal":null,"off":"none","xhigh":"xhigh"}}'::jsonb),
    ('gpt-realtime-2.1', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":"minimal","off":null,"xhigh":"xhigh"}}'::jsonb),
    ('k3', '{"reasoning":true,"thinkingFormat":"anthropic-adaptive","thinkingLevelMap":{"high":"high","low":"low","max":"max","medium":null,"minimal":null,"off":null,"xhigh":null}}'::jsonb),
    ('k3-256k', '{"reasoning":true,"thinkingFormat":"anthropic-adaptive","thinkingLevelMap":{"high":"high","low":"low","max":"max","medium":null,"minimal":null,"off":null,"xhigh":null}}'::jsonb),
    ('kimi-for-coding', '{"reasoning":true,"thinkingFormat":"anthropic-adaptive"}'::jsonb),
    ('kimi-for-coding-highspeed', '{"reasoning":true,"thinkingFormat":"anthropic-adaptive"}'::jsonb),
    ('o1', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":null,"xhigh":null}}'::jsonb),
    ('o1-pro', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":null,"xhigh":null}}'::jsonb),
    ('o3', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":null,"xhigh":null}}'::jsonb),
    ('o3-mini', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":null,"xhigh":null}}'::jsonb),
    ('o3-pro', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":null,"xhigh":null}}'::jsonb),
    ('o4-mini', '{"reasoning":true,"thinkingFormat":"openai","thinkingLevelMap":{"high":"high","low":"low","max":null,"medium":"medium","minimal":null,"off":null,"xhigh":null}}'::jsonb)
)
UPDATE "model_catalog" AS catalog
SET "capabilities" = ((((catalog."capabilities" - 'reasoning') - 'reasoningEffort') - 'thinkingFormat') - 'thinkingLevelMap') || reviewed."reasoning_bundle",
    "updated_at" = now()
FROM reviewed
WHERE catalog."canonical_model_id" = reviewed."canonical_model_id"
  AND catalog."capabilities" IS DISTINCT FROM ((((catalog."capabilities" - 'reasoning') - 'reasoningEffort') - 'thinkingFormat') - 'thinkingLevelMap') || reviewed."reasoning_bundle";
--> statement-breakpoint
WITH unverified("canonical_model_id") AS (
  VALUES
    ('MiniMax-M2.7'),
    ('MiniMax-M2.7-highspeed'),
    ('MiniMax-M3'),
    ('aion-2.0'),
    ('aion-3.0'),
    ('aion-3.0-mini'),
    ('big-pickle'),
    ('claude-fable-5:batch'),
    ('claude-fable-latest'),
    ('claude-haiku-4-5-20251001-v1:0'),
    ('claude-haiku-4.5:batch'),
    ('claude-haiku-latest'),
    ('claude-opus-4'),
    ('claude-opus-4-1'),
    ('claude-opus-4-1-20250805'),
    ('claude-opus-4-1-20250805-v1:0'),
    ('claude-opus-4-5-20251101-v1:0'),
    ('claude-opus-4-6-v1'),
    ('claude-opus-4.1:batch'),
    ('claude-opus-4.5:batch'),
    ('claude-opus-4.6:batch'),
    ('claude-opus-4.7-fast'),
    ('claude-opus-4.7:batch'),
    ('claude-opus-4.8:batch'),
    ('claude-opus-5-fast'),
    ('claude-opus-latest'),
    ('claude-sonnet-4-5-20250929-v1:0'),
    ('claude-sonnet-4.5:batch'),
    ('claude-sonnet-5:batch'),
    ('claude-sonnet-latest'),
    ('cosmos-reason2-8b'),
    ('deepseek-chat-v3.1'),
    ('deepseek-r1-0528'),
    ('deepseek-v3.1'),
    ('deepseek-v3.1-terminus'),
    ('deepseek-v3.2-exp'),
    ('deepseek-v3.2-thinking'),
    ('deepseek.r1-v1:0'),
    ('deepseek.v3-v1:0'),
    ('free'),
    ('fugu-ultra'),
    ('fusion'),
    ('gemini-2.5-flash-lite:batch'),
    ('gemini-2.5-flash:batch'),
    ('gemini-2.5-pro-preview'),
    ('gemini-2.5-pro-preview-05-06'),
    ('gemini-2.5-pro:batch'),
    ('gemini-3-flash-preview:batch'),
    ('gemini-3-pro-image'),
    ('gemini-3-pro-preview'),
    ('gemini-3.1-flash-lite:batch'),
    ('gemini-3.1-pro'),
    ('gemini-3.1-pro-preview:batch'),
    ('gemini-3.5-flash-lite:batch'),
    ('gemini-3.5-flash:batch'),
    ('gemini-3.6-flash:batch'),
    ('gemini-pro-latest'),
    ('glm-4.6'),
    ('glm-4.6v'),
    ('glm-4.6v-flash'),
    ('glm-4.7-flash'),
    ('glm-4.7-flashx'),
    ('glm-5.2-fast'),
    ('glm-5p1'),
    ('glm-5p1-fast'),
    ('glm-5p2'),
    ('glm-5p2-fast'),
    ('gpt-5-codex'),
    ('gpt-5-mini:batch'),
    ('gpt-5-nano:batch'),
    ('gpt-5.1-codex'),
    ('gpt-5.1-codex-max'),
    ('gpt-5.1-codex-mini'),
    ('gpt-5.1-thinking'),
    ('gpt-5.1:batch'),
    ('gpt-5.2-codex'),
    ('gpt-5.2:batch'),
    ('gpt-5.4-mini:batch'),
    ('gpt-5.4-nano:batch'),
    ('gpt-5.4:batch'),
    ('gpt-5.5:batch'),
    ('gpt-5.6-luna-pro'),
    ('gpt-5.6-sol-pro'),
    ('gpt-5.6-terra-pro'),
    ('gpt-5:batch'),
    ('gpt-latest'),
    ('gpt-mini-latest'),
    ('gpt-oss-120b'),
    ('gpt-oss-120b-1:0'),
    ('gpt-oss-20b'),
    ('gpt-oss-20b-1:0'),
    ('gpt-oss-safeguard-20b'),
    ('grok-4.1-fast-reasoning'),
    ('grok-4.20'),
    ('grok-4.20-multi-agent'),
    ('grok-4.20-multi-agent-beta'),
    ('grok-4.20-reasoning-beta'),
    ('grok-latest'),
    ('hy3'),
    ('hy3-preview'),
    ('inkling'),
    ('interfaze-beta'),
    ('jp.anthropic.claude-haiku-4-5-20251001-v1:0'),
    ('jp.anthropic.claude-opus-4-7'),
    ('jp.anthropic.claude-opus-4-8'),
    ('jp.anthropic.claude-opus-5'),
    ('jp.anthropic.claude-sonnet-4-5-20250929-v1:0'),
    ('jp.anthropic.claude-sonnet-4-6'),
    ('jp.anthropic.claude-sonnet-5'),
    ('kat-coder-pro-v2'),
    ('kimi-k2p6'),
    ('kimi-k2p6-fast'),
    ('kimi-k2p6-turbo'),
    ('kimi-k2p7-code'),
    ('kimi-k2p7-code-fast'),
    ('kimi-k3-fast'),
    ('kimi-latest'),
    ('laguna-m.1'),
    ('laguna-s-2.1'),
    ('laguna-xs-2.1'),
    ('ling-3.0-flash'),
    ('llama-3.1-nemotron-nano-8b-v1'),
    ('llama-3.1-nemotron-nano-vl-8b-v1'),
    ('llama-3.1-nemotron-ultra-253b-v1'),
    ('llama-3.3-nemotron-super-49b-v1'),
    ('llama-3.3-nemotron-super-49b-v1.5'),
    ('longcat-2.0'),
    ('magistral-medium'),
    ('magistral-medium-latest'),
    ('magistral-small'),
    ('mai-code-1-flash-picker'),
    ('mercury-2'),
    ('minimax-m1'),
    ('minimax-m2'),
    ('minimax-m2.1'),
    ('minimax-m2.1-lightning'),
    ('minimax-m2.5-highspeed'),
    ('minimax-m2p7'),
    ('minimax-m3:batch'),
    ('minimax.minimax-m2'),
    ('minimax.minimax-m2.1'),
    ('minimax.minimax-m2.5'),
    ('mistral-medium-2604'),
    ('mistral-medium-3.5'),
    ('mistral-medium-3.5-128b'),
    ('mistral-medium-latest'),
    ('mistral-small-2603'),
    ('mistral-small-4-119b-2603'),
    ('mistral-small-latest'),
    ('mistral.magistral-small-2509'),
    ('moonshot.kimi-k2-thinking'),
    ('moonshotai.kimi-k2.5'),
    ('muse-spark-1.1'),
    ('nemotron-3-120b-a12b'),
    ('nemotron-3-nano-30b-a3b'),
    ('nemotron-3-nano-omni-30b-a3b-reasoning'),
    ('nemotron-3-super-120b-a12b'),
    ('nemotron-3-ultra'),
    ('nemotron-3-ultra-550b-a55b'),
    ('nemotron-nano-12b-v2-vl'),
    ('nemotron-nano-9b-v2'),
    ('nex-n2-mini'),
    ('nex-n2-pro'),
    ('north-mini-code'),
    ('nova-2-lite'),
    ('nova-2-lite-v1'),
    ('nova-2-lite-v1:0'),
    ('nvidia-nemotron-nano-9b-v2'),
    ('nvidia.nemotron-nano-3-30b'),
    ('nvidia.nemotron-super-3-120b'),
    ('o3-deep-research'),
    ('o3-mini-high'),
    ('o4-mini-deep-research'),
    ('o4-mini-high'),
    ('qwen-3-14b'),
    ('qwen-3-235b'),
    ('qwen-3-30b'),
    ('qwen-3-32b'),
    ('qwen-3.6-max-preview'),
    ('qwen-plus-2025-07-28:thinking'),
    ('qwen.qwen3-32b-v1:0'),
    ('qwen.qwen3-coder-next'),
    ('qwen3-14b'),
    ('qwen3-235b-a22b-thinking'),
    ('qwen3-235b-a22b-thinking-2507'),
    ('qwen3-30b-a3b'),
    ('qwen3-30b-a3b-fp8'),
    ('qwen3-30b-a3b-thinking-2507'),
    ('qwen3-8b'),
    ('qwen3-max-thinking'),
    ('qwen3-vl-235b-a22b-thinking'),
    ('qwen3-vl-30b-a3b-thinking'),
    ('qwen3-vl-8b-thinking'),
    ('qwen3-vl-thinking'),
    ('qwen3.5-122b-a10b'),
    ('qwen3.5-27b'),
    ('qwen3.5-35b-a3b'),
    ('qwen3.5-397b-a17b'),
    ('qwen3.5-9b'),
    ('qwen3.5-flash'),
    ('qwen3.5-flash-02-23'),
    ('qwen3.5-plus'),
    ('qwen3.5-plus-02-15'),
    ('qwen3.5-plus-20260420'),
    ('qwen3.6-35b-a3b'),
    ('qwen3.6-max-preview'),
    ('qwen3.7-flash'),
    ('qwen3p7-plus'),
    ('seed-1.6'),
    ('seed-1.6-flash'),
    ('seed-1.8'),
    ('seed-2.0-lite'),
    ('seed-2.0-mini'),
    ('solar-pro-3'),
    ('trinity-large-thinking'),
    ('writer.palmyra-x4-v1:0'),
    ('writer.palmyra-x5-v1:0'),
    ('xai.grok-4.3'),
    ('zai.glm-4.7-flash'),
    ('zai.glm-5')
)
UPDATE "model_catalog" AS catalog
SET "capabilities" = ((catalog."capabilities" - 'reasoning') - 'reasoningEffort') - 'thinkingFormat' - 'thinkingLevelMap',
    "updated_at" = now()
FROM unverified
WHERE catalog."canonical_model_id" = unverified."canonical_model_id"
  AND catalog."capabilities" @> '{"reasoning":true}'::jsonb
  AND (
    NOT (catalog."capabilities" ? 'thinkingFormat')
    OR catalog."capabilities" ->> 'thinkingFormat' NOT IN (
      'fixed', 'openai', 'anthropic', 'anthropic-adaptive', 'google', 'openrouter',
      'deepseek', 'together', 'zai', 'qwen', 'qwen-chat-template', 'agnes',
      'string-thinking', 'ant-ling'
    )
  );
