INSERT INTO "model_catalog" ("id", "name", "canonical_model_id", "aliases", "model_type", "capabilities", "sort_order") VALUES
('catalog-claude-fable-5', 'Claude Fable 5', 'claude-fable-5', '["anthropic/claude-fable-5"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"anthropic","thinkingLevelMap":{"off":null,"xhigh":"xhigh","max":"max"}}'::jsonb, 40),
('catalog-claude-haiku-4-5', 'Claude Haiku 4.5', 'claude-haiku-4-5', '["anthropic/claude-haiku-4-5","claude-haiku-4-5-20251001"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"anthropic"}'::jsonb, 41),
('catalog-claude-opus-4-6', 'Claude Opus 4.6', 'claude-opus-4-6', '["anthropic/claude-opus-4-6"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"anthropic","thinkingLevelMap":{"max":"max"}}'::jsonb, 42),
('catalog-claude-opus-4-7', 'Claude Opus 4.7', 'claude-opus-4-7', '["anthropic/claude-opus-4-7"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"anthropic","thinkingLevelMap":{"xhigh":"xhigh","max":"max"}}'::jsonb, 43),
('catalog-claude-opus-4-8', 'Claude Opus 4.8', 'claude-opus-4-8', '["anthropic/claude-opus-4-8","claude-opus-4-8-fast"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"anthropic","thinkingLevelMap":{"xhigh":"xhigh","max":"max"}}'::jsonb, 44),
('catalog-claude-sonnet-4-6', 'Claude Sonnet 4.6', 'claude-sonnet-4-6', '["anthropic/claude-sonnet-4-6"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"anthropic","thinkingLevelMap":{"max":"max"}}'::jsonb, 45),
('catalog-claude-sonnet-5', 'Claude Sonnet 5', 'claude-sonnet-5', '["anthropic/claude-sonnet-5"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"anthropic","thinkingLevelMap":{"xhigh":"xhigh","max":"max"}}'::jsonb, 46),
('catalog-gemini-3-flash', 'Gemini 3 Flash', 'gemini-3-flash-preview', '["google/gemini-3-flash-preview","gemini-3-flash","gemini-flash-latest"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"google","thinkingLevelMap":{"off":null}}'::jsonb, 50),
('catalog-gemini-3-1-flash-lite', 'Gemini 3.1 Flash Lite', 'gemini-3.1-flash-lite', '["google/gemini-3.1-flash-lite","gemini-3.1-flash-lite-preview","gemini-flash-lite-latest"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"google","thinkingLevelMap":{"off":null}}'::jsonb, 51),
('catalog-gemini-3-1-pro', 'Gemini 3.1 Pro', 'gemini-3.1-pro-preview', '["google/gemini-3.1-pro-preview","gemini-3.1-pro-preview-customtools"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"google","thinkingLevelMap":{"off":null,"minimal":null,"low":"LOW","medium":null,"high":"HIGH"}}'::jsonb, 52),
('catalog-gemini-3-5-flash', 'Gemini 3.5 Flash', 'gemini-3.5-flash', '["google/gemini-3.5-flash"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"google","thinkingLevelMap":{"off":null}}'::jsonb, 53),
('catalog-gpt-5-3-codex', 'GPT-5.3 Codex', 'gpt-5.3-codex', '["openai/gpt-5.3-codex"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"openai","thinkingLevelMap":{"off":"none","xhigh":"xhigh"}}'::jsonb, 60),
('catalog-gpt-5-4', 'GPT-5.4', 'gpt-5.4', '["openai/gpt-5.4"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"openai","thinkingLevelMap":{"off":"none","xhigh":"xhigh"}}'::jsonb, 61),
('catalog-gpt-5-4-mini', 'GPT-5.4 Mini', 'gpt-5.4-mini', '["openai/gpt-5.4-mini"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"openai","thinkingLevelMap":{"off":"none","xhigh":"xhigh"}}'::jsonb, 62),
('catalog-gpt-5-4-nano', 'GPT-5.4 Nano', 'gpt-5.4-nano', '["openai/gpt-5.4-nano"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"openai","thinkingLevelMap":{"off":"none","xhigh":"xhigh"}}'::jsonb, 63),
('catalog-gpt-5-4-pro', 'GPT-5.4 Pro', 'gpt-5.4-pro', '["openai/gpt-5.4-pro"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"openai","thinkingLevelMap":{"off":null,"xhigh":"xhigh"}}'::jsonb, 64),
('catalog-gpt-5-5', 'GPT-5.5', 'gpt-5.5', '["openai/gpt-5.5"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"openai","thinkingLevelMap":{"off":"none","minimal":null,"xhigh":"xhigh"}}'::jsonb, 65),
('catalog-gpt-5-5-pro', 'GPT-5.5 Pro', 'gpt-5.5-pro', '["openai/gpt-5.5-pro"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"openai","thinkingLevelMap":{"off":null,"minimal":null,"low":null,"xhigh":"xhigh"}}'::jsonb, 66),
('catalog-grok-4-20-non-reasoning', 'Grok 4.20 Non-Reasoning', 'grok-4.20-0309-non-reasoning', '["xai/grok-4.20-0309-non-reasoning","x-ai/grok-4.20-non-reasoning"]'::jsonb, 'chat', '{"vision":true,"tools":true,"systemPrompt":true}'::jsonb, 70),
('catalog-grok-4-20-reasoning', 'Grok 4.20 Reasoning', 'grok-4.20-0309-reasoning', '["xai/grok-4.20-0309-reasoning","x-ai/grok-4.20-reasoning"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"fixed","thinkingLevelMap":{"off":null,"minimal":null,"low":null,"medium":null,"high":"default","xhigh":null,"max":null}}'::jsonb, 71),
('catalog-grok-4-3', 'Grok 4.3', 'grok-4.3', '["xai/grok-4.3","x-ai/grok-4.3"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"fixed","thinkingLevelMap":{"off":null,"minimal":null,"low":null,"medium":null,"high":"default","xhigh":null,"max":null}}'::jsonb, 72),
('catalog-grok-4-5', 'Grok 4.5', 'grok-4.5', '["xai/grok-4.5","x-ai/grok-4.5"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"fixed","thinkingLevelMap":{"off":null,"minimal":null,"low":null,"medium":null,"high":"default","xhigh":null,"max":null}}'::jsonb, 73),
('catalog-grok-build-0-1', 'Grok Build 0.1', 'grok-build-0.1', '["xai/grok-build-0.1","x-ai/grok-build-0.1"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"fixed","thinkingLevelMap":{"off":null,"minimal":null,"low":null,"medium":null,"high":"default","xhigh":null,"max":null}}'::jsonb, 74),
('catalog-glm-4-7', 'GLM 4.7', 'glm-4.7', '["zai/glm-4.7","zhipu/glm-4.7","volcengine/glm-4.7"]'::jsonb, 'chat', '{"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"zai"}'::jsonb, 80),
('catalog-glm-5-turbo', 'GLM 5 Turbo', 'glm-5-turbo', '["zai/glm-5-turbo","zhipu/glm-5-turbo","volcengine/glm-5-turbo"]'::jsonb, 'chat', '{"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"zai"}'::jsonb, 81),
('catalog-glm-5-1', 'GLM 5.1', 'glm-5.1', '["zai/glm-5.1","zhipu/glm-5.1","volcengine/glm-5.1"]'::jsonb, 'chat', '{"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"zai"}'::jsonb, 82),
('catalog-glm-5-2', 'GLM 5.2', 'glm-5.2', '["zai/glm-5.2","zhipu/glm-5.2","volcengine/glm-5.2"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"zai","thinkingLevelMap":{"minimal":null,"low":"high","medium":"high","high":"high","max":"max"}}'::jsonb, 83),
('catalog-glm-5v-turbo', 'GLM 5V Turbo', 'glm-5v-turbo', '["zai/glm-5v-turbo","zhipu/glm-5v-turbo","volcengine/glm-5v-turbo"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"zai"}'::jsonb, 84),
('catalog-kimi-k2-5', 'Kimi K2.5', 'kimi-k2.5', '["moonshot/kimi-k2.5","moonshotai/kimi-k2.5"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"deepseek","thinkingLevelMap":{"minimal":null,"low":null,"medium":null,"high":"high","xhigh":null,"max":null}}'::jsonb, 90),
('catalog-kimi-k2-6', 'Kimi K2.6', 'kimi-k2.6', '["moonshot/kimi-k2.6","moonshotai/kimi-k2.6"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"deepseek","thinkingLevelMap":{"minimal":null,"low":null,"medium":null,"high":"high","xhigh":null,"max":null}}'::jsonb, 91),
('catalog-kimi-k2-7-code', 'Kimi K2.7 Code', 'kimi-k2.7-code', '["moonshot/kimi-k2.7-code","moonshotai/kimi-k2.7-code"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"fixed","thinkingLevelMap":{"off":null,"minimal":null,"low":null,"medium":null,"high":"default","xhigh":null,"max":null}}'::jsonb, 92),
('catalog-kimi-k2-7-code-highspeed', 'Kimi K2.7 Code HighSpeed', 'kimi-k2.7-code-highspeed', '["moonshot/kimi-k2.7-code-highspeed","moonshotai/kimi-k2.7-code-highspeed"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"fixed","thinkingLevelMap":{"off":null,"minimal":null,"low":null,"medium":null,"high":"default","xhigh":null,"max":null}}'::jsonb, 93),
('catalog-minimax-m2-7', 'MiniMax M2.7', 'MiniMax-M2.7', '["minimax/MiniMax-M2.7","MiniMaxAI/MiniMax-M2.7"]'::jsonb, 'chat', '{"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"anthropic"}'::jsonb, 100),
('catalog-minimax-m2-7-highspeed', 'MiniMax M2.7 HighSpeed', 'MiniMax-M2.7-highspeed', '["minimax/MiniMax-M2.7-highspeed"]'::jsonb, 'chat', '{"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"anthropic"}'::jsonb, 101),
('catalog-minimax-m3', 'MiniMax M3', 'MiniMax-M3', '["minimax/MiniMax-M3","MiniMaxAI/MiniMax-M3"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"anthropic"}'::jsonb, 102),
('catalog-composer-2-5', 'Composer 2.5', 'composer-2.5', '["cursor/composer-2.5","composer-2.5-fast"]'::jsonb, 'chat', '{"vision":true,"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"fixed","thinkingLevelMap":{"off":null,"minimal":null,"low":null,"medium":null,"high":"default","xhigh":null,"max":null}}'::jsonb, 110),
('catalog-deepseek-v4-flash', 'DeepSeek V4 Flash', 'deepseek-v4-flash', '["deepseek/deepseek-v4-flash"]'::jsonb, 'chat', '{"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"deepseek","thinkingLevelMap":{"minimal":null,"low":null,"medium":null,"high":"high","max":"max"}}'::jsonb, 120),
('catalog-deepseek-v4-pro', 'DeepSeek V4 Pro', 'deepseek-v4-pro', '["deepseek/deepseek-v4-pro"]'::jsonb, 'chat', '{"tools":true,"reasoning":true,"systemPrompt":true,"thinkingFormat":"deepseek","thinkingLevelMap":{"minimal":null,"low":null,"medium":null,"high":"high","max":"max"}}'::jsonb, 121)
ON CONFLICT ("canonical_model_id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "aliases" = EXCLUDED."aliases",
  "model_type" = EXCLUDED."model_type",
  "capabilities" = EXCLUDED."capabilities",
  "sort_order" = EXCLUDED."sort_order",
  "enabled" = true;
--> statement-breakpoint

UPDATE "model_catalog"
SET "capabilities" = jsonb_set("capabilities", '{thinkingFormat}', '"anthropic-adaptive"'::jsonb)
WHERE "canonical_model_id" IN (
  'claude-fable-5', 'claude-opus-4-6', 'claude-opus-4-7',
  'claude-opus-4-8', 'claude-sonnet-4-6', 'claude-sonnet-5'
);
